# Generated by Django 6.0.3 on 2026-04-06 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='actor',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL),
        ),
    ]
