# Generated by Django 6.0.3 on 2026-04-12 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_permissions', '0005_documentpermissionrequestmodel'),
        ('notifications', '0003_remove_notificationmodel_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='permission_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='document_permissions.documentpermissionrequestmodel'),
        ),
    ]
