# Generated by Django 6.0.3 on 2026-04-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentdeletiondecisionmodel_decision'),
        ('notifications', '0004_notificationmodel_permission_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='deletion_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='documents.documentdeletionrequestmodel'),
        ),
    ]
