# Generated by Django 6.0.3 on 2026-04-16 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentdeletiondecisionmodel_decision'),
        ('versions', '0002_alter_versionsmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='versionsmodel',
            index=models.Index(fields=['document', 'is_active'], name='versions_documen_4094a5_idx'),
        ),
    ]
