# Generated by Django 6.0.2 on 2026-03-25 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermissionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_type', models.CharField(choices=[('READ', 'READ'), ('WRITE', 'WRITE'), ('APPROVE', 'APPROVE'), ('DELETE', 'DELETE')], default='READ', max_length=16)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions_document', to='documents.documentmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_permissions',
                'indexes': [models.Index(fields=['user_id', 'document_id'], name='document_pe_user_id_7c0b5b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'document_id', 'permission_type'), name='unique_user_document_permission')],
            },
        ),
    ]
