# Generated by Django 6.0.3 on 2026-03-28 00:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermissionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_type', models.CharField(choices=[('READ', 'Read Only'), ('WRITE', 'Write/Edit'), ('APPROVE', 'Approve/Review'), ('DELETE', 'Full Owner/Delete')], default='READ', max_length=16)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_permissions',
            },
        ),
    ]
