# Generated by Django 6.0.3 on 2026-03-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_permissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpermissionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentpermissionmodel',
            index=models.Index(fields=['user', 'document'], name='document_pe_user_id_c60610_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpermissionmodel',
            constraint=models.UniqueConstraint(fields=('user', 'document'), name='unique_user_document_permission'),
        ),
    ]
