# Generated by Django 6.0.3 on 2026-04-09 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_permissions', '0003_initial'),
        ('documents', '0002_initial'),
        ('versions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentpermissionmodel',
            name='unique_user_document_permission',
        ),
        migrations.AddField(
            model_name='documentpermissionmodel',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_permissions', to='versions.versionsmodel'),
        ),
        migrations.AddConstraint(
            model_name='documentpermissionmodel',
            constraint=models.UniqueConstraint(fields=('user', 'document', 'version'), name='unique_user_document_permission'),
        ),
    ]
