# Generated by Django 6.0.3 on 2026-04-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_permissions', '0005_documentpermissionrequestmodel'),
        ('versions', '0002_alter_versionsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpermissionrequestmodel',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='versions.versionsmodel'),
        ),
    ]
