# Generated by Django 6.0.2 on 2026-03-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='versions.versions'),
        ),
    ]
