# Generated by Django 6.0.3 on 2026-04-16 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
        ('versions', '0002_alter_versionsmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reviewmodel',
            index=models.Index(fields=['reviewer', 'review_status'], name='reviews_reviewe_65cf59_idx'),
        ),
    ]
