# Generated by Django 6.0.2 on 2026-03-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesmodel',
            name='role_name',
            field=models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('reader', 'Reader'), ('administrator', 'Administrator')], max_length=50, unique=True),
        ),
    ]
