# Generated by Django 6.0.3 on 2026-03-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='documentmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('created_by', 'title'), name='unique_user_active_title'),
        ),
    ]
