# Generated by Django 6.0.3 on 2026-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentdeletiondecisionmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdeletiondecisionmodel',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
