# Generated by Django 6.0.3 on 2026-04-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentdeletiondecisionmodel_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdeletiondecisionmodel',
            name='decision',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10, null=True),
        ),
    ]
